
export const Data = [
    { id: Math.random(), price: 80 ,image: "images/1.1.jpeg", title: "وجبة الفطار", discription: "نقدم لكم الذ واطعم الوجبات كل ما تشتهيه من وجبات الفطار"},
    { id: Math.random(), price: 70 , image: "images/1.2.jpeg", title: "وجبة الفطار", discription: "نقدم لكم الذ واطعم الوجبات كل ما تشتهيه من وجبات الفطار"},
    { id: Math.random(), price: 95 , image: "images/1.3.jpeg", title: "وجبة الفطار", discription: "نقدم لكم الذ واطعم الوجبات كل ما تشتهيه من وجبات الفطار"},
    { id: Math.random(), price: 85 , image: "images/1.4.jpeg", title: "وجبة الفطار", discription: "نقدم لكم الذ واطعم الوجبات كل ما تشتهيه من وجبات الفطار"},
    { id: Math.random(), price: 100 , image: "images/1.5.jpeg", title: "وجبة الفطار", discription: "نقدم لكم الذ واطعم الوجبات كل ما تشتهيه من وجبات الفطار"},
    { id: Math.random(), price: 105 , image: "images/1.6.jpeg", title: "وجبة الفطار", discription: "نقدم لكم الذ واطعم الوجبات كل ما تشتهيه من وجبات الفطار"},
    { id: Math.random(), price: 60 , image: "images/1.7.jpeg", title: "وجبة الفطار", discription: "نقدم لكم الذ واطعم الوجبات كل ما تشتهيه من وجبات الفطار"},
    { id: Math.random(), price: 220 , image: "images/2.1.jpeg", title: "وجبة الغداء", discription: "استمتع معنا بوجبات الغداء الصحيه"},
    { id: Math.random(), price: 400 , image: "images/2.2.jpeg", title: "وجبة الغداء", discription: "استمتع معنا بوجبات الغداء الصحيه"},
    { id: Math.random(), price: 180 , image: "images/2.3.jpeg", title: "وجبة الغداء", discription: "استمتع معنا بوجبات الغداء الصحيه"},
    { id: Math.random(), price: 200 , image: "images/2.4.jpeg", title: "وجبة الغداء", discription: "استمتع معنا بوجبات الغداء الصحيه"},
    { id: Math.random(), price: 300 , image: "images/2.5.jpeg", title: "وجبة الغداء", discription: "استمتع معنا بوجبات الغداء الصحيه"},
    { id: Math.random(), price: 250 , image: "images/3.1.jpeg", title: "وجبة العشاء", discription: "شارك اهلك واصدقائك افخم واطعم الماكولات في وجبة العشاء"},
    { id: Math.random(), price: 500 , image: "images/3.2.jpeg", title: "وجبة العشاء", discription: "شارك اهلك واصدقائك افخم واطعم الماكولات في وجبة العشاء"},
    { id: Math.random(), price: 150 , image: "images/3.3.jpeg", title: "وجبة العشاء", discription: "شارك اهلك واصدقائك افخم واطعم الماكولات في وجبة العشاء"},
    { id: Math.random(), price: 180 , image: "images/3.4.jpeg", title: "وجبة العشاء", discription: "شارك اهلك واصدقائك افخم واطعم الماكولات في وجبة العشاء"},
    { id: Math.random(), price: 250 , image: "images/3.5.jpeg", title: "وجبة العشاء", discription: "شارك اهلك واصدقائك افخم واطعم الماكولات في وجبة العشاء"},
    { id: Math.random(), price: 320 , image: "images/4.1.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
    { id: Math.random(), price: 370 , image: "images/4.2.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
    { id: Math.random(), price: 400 , image: "images/4.3.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
    { id: Math.random(), price: 100 , image: "images/4.4.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
    { id: Math.random(), price: 150 , image: "images/4.5.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
    { id: Math.random(), price: 200 , image: "images/4.6.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
    { id: Math.random(), price: 100 , image: "images/4.7.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
    { id: Math.random(), price: 240 , image: "images/4.8.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
    { id: Math.random(), price: 280 , image: "images/4.9.jpeg", title: "الحلويات", discription: "تذوق جميع انواع الحلويات الشهيه واجمل التشكيلات"},
]